### ISSUE TITLE
{{ range .Backends -}} doesn't de-register on pod delete

### ISSUE THREAD

**Issue by tschirmer** [mittwald/kube-httpcache#14]
I've got a VCL running health checks:

```
{{ range .Backends }}
backend be-{{ .Name }} {
  .host = "{{ .Host }}";
  .port = "{{ .Port }}";
  .first_byte_timeout = 600s;
  .probe = {
      .url = "/health_check.php";
      .timeout = 2s;
      .interval = 5s;
      .window = 10;
      .threshold = 5;
  }
}
{{- end }}
```

Now even with 1 backend in the service to discover, we're getting multiple health checks (to the point it's overloading our server). (this is a single pod's logs here). I'm assuming it's been registered more than once in the range.Backends, but I could be wrong.

```
127.0.0.1 -  29/Jan/2020:23:40:46 +0000 "GET /health_check.php" 200
10.0.1.179:80 10.0.1.139 - - [29/Jan/2020:23:40:43 +0000] "GET /health_check.php HTTP/1.1" 200 517 "-" "-"
127.0.0.1 -  29/Jan/2020:23:40:46 +0000 "GET /health_check.php" 200
10.0.1.179:80 10.0.1.139 - - [29/Jan/2020:23:40:43 +0000] "GET /health_check.php HTTP/1.1" 200 517 "-" "-"
127.0.0.1 -  29/Jan/2020:23:40:46 +0000 "GET /health_check.php" 200
10.0.1.179:80 10.0.1.139 - - [29/Jan/2020:23:40:43 +0000] "GET /health_check.php HTTP/1.1" 200 517 "-" "-"
127.0.0.1 -  29/Jan/2020:23:40:46 +0000 "GET /health_check.php" 200
10.0.1.179:80 10.0.1.139 - - [29/Jan/2020:23:40:43 +0000] "GET /health_check.php HTTP/1.1" 200 517 "-" "-"
127.0.0.1 -  29/Jan/2020:23:40:46 +0000 "GET /health_check.php" 200
10.0.1.179:80 10.0.1.139 - - [29/Jan/2020:23:40:43 +0000] "GET /health_check.php HTTP/1.1" 200 517 "-" "-"
127.0.0.1 -  29/Jan/2020:23:40:46 +0000 "GET /health_check.php" 200
127.0.0.1 -  29/Jan/2020:23:40:46 +0000 "GET /health_check.php" 200
10.0.1.179:80 10.0.1.139 - - [29/Jan/2020:23:40:44 +0000] "GET /health_check.php HTTP/1.1" 200 517 "-" "-"
10.0.1.179:80 10.0.1.139 - - [29/Jan/2020:23:40:44 +0000] "GET /health_check.php HTTP/1.1" 200 517 "-" "-"
127.0.0.1 -  29/Jan/2020:23:40:46 +0000 "GET /health_check.php" 200
10.0.1.179:80 10.0.1.139 - - [29/Jan/2020:23:40:44 +0000] "GET /health_check.php HTTP/1.1" 200 517 "-" "-"
127.0.0.1 -  29/Jan/2020:23:40:46 +0000 "GET /health_check.php" 200
10.0.1.179:80 10.0.1.139 - - [29/Jan/2020:23:40:44 +0000] "GET /health_check.php HTTP/1.1" 200 517 "-" "-"
127.0.0.1 -  29/Jan/2020:23:40:46 +0000 "GET /health_check.php" 200
10.0.1.179:80 10.0.1.139 - - [29/Jan/2020:23:40:44 +0000] "GET /health_check.php HTTP/1.1" 200 517 "-" "-"
127.0.0.1 -  29/Jan/2020:23:40:46 +0000 "GET /health_check.php" 200
127.0.0.1 -  29/Jan/2020:23:40:46 +0000 "GET /health_check.php" 200
10.0.1.179:80 10.0.1.139 - - [29/Jan/2020:23:40:44 +0000] "GET /health_check.php HTTP/1.1" 200 517 "-" "-"
10.0.1.179:80 10.0.1.139 - - [29/Jan/2020:23:40:44 +0000] "GET /health_check.php HTTP/1.1" 200 517 "-" "-"
127.0.0.1 -  29/Jan/2020:23:40:46 +0000 "GET /health_check.php" 200
127.0.0.1 -  29/Jan/2020:23:40:46 +0000 "GET /health_check.php" 200
10.0.1.179:80 10.0.1.139 - - [29/Jan/2020:23:40:44 +0000] "GET /health_check.php HTTP/1.1" 200 517 "-" "-"
10.0.1.179:80 10.0.1.139 - - [29/Jan/2020:23:40:44 +0000] "GET /health_check.php HTTP/1.1" 200 517 "-" "-"
127.0.0.1 -  29/Jan/2020:23:40:46 +0000 "GET /health_check.php" 200
10.0.1.179:80 10.0.1.139 - - [29/Jan/2020:23:40:44 +0000] "GET /health_check.php HTTP/1.1" 200 517 "-" "-"
```

**Comment by martin-helmich** [comment]
Ouch. This should not happen.

Could you dump the compiled VCL file with `varnishadm` and the `vcl.list`/`vcl.show` commands, to check how the backend definitions are actually rendered?

**Comment by tschirmer** [comment]
```
vcl.show boot
200
vcl 4.0;

import std;
import directors;
# The minimal Varnish version is 4.0
# For SSL offloading, pass the following header in your proxy server or load balancer: 'X-Forwarded-Proto: https'


backend be-application-deployment-6695f79d98-rff4k {
  .host = "10.0.1.150";
  .port = "80";
  .first_byte_timeout = 600s;
  .probe = {
      .url = "/health_check.php";
      .timeout = 2s;
      .interval = 5s;
      .window = 10;
      .threshold = 5;
  }
}
backend be-application-deployment-6695f79d98-n5g5j {
  .host = "10.0.1.161";
  .port = "80";
  .first_byte_timeout = 600s;
  .probe = {
      .url = "/health_check.php";
      .timeout = 2s;
      .interval = 5s;
      .window = 10;
      .threshold = 5;
  }
}
backend be-application-deployment-6695f79d98-45ntm {
  .host = "10.0.1.167";
  .port = "80";
  .first_byte_timeout = 600s;
  .probe = {
      .url = "/health_check.php";
      .timeout = 2s;
      .interval = 5s;
      .window = 10;
      .threshold = 5;
  }
}
backend be-application-deployment-6695f79d98-qzs5p {
  .host = "10.0.1.238";
  .port = "80";
  .first_byte_timeout = 600s;
  .probe = {
      .url = "/health_check.php";
      .timeout = 2s;
      .interval = 5s;
      .window = 10;
      .threshold = 5;
  }
}

backend be-primary {
  .host = "10.0.1.150";
  .port = "80";
  .first_byte_timeout = 600s;
}

acl purge {
  "127.0.0.1";
  "localhost";
  "::1";
  "192.168.0.0/16";
  "10.0.0.0/16";
  "10.0.1.150";
  "10.0.1.161";
  "10.0.1.167";
  "10.0.1.238";
}

sub vcl_init {
  new lb = directors.round_robin();

  lb.add_backend(be-primary);

  lb.add_backend(be-application-deployment-6695f79d98-rff4k);
  lb.add_backend(be-application-deployment-6695f79d98-n5g5j);
  lb.add_backend(be-application-deployment-6695f79d98-45ntm);
  lb.add_backend(be-application-deployment-6695f79d98-qzs5p);

}

sub vcl_recv {
    if (req.method == "PURGE") {
        if (client.ip !~ purge) {
            return (synth(405, "Method not allowed"));
        }
        # To use the X-Pool header for purging varnish during automated deployments, make sure the X-Pool header
        # has been added to the response in your backend server config. This is used, for example, by the
        # capistrano-magento2 gem for purging old content from varnish during it's deploy routine.
        if (!req.http.X-Magento-Tags-Pattern && !req.http.X-Pool) {
            return (synth(400, "X-Magento-Tags-Pattern or X-Pool header required"));
        }
        if (req.http.X-Magento-Tags-Pattern) {
          ban("obj.http.X-Magento-Tags ~ " + req.http.X-Magento-Tags-Pattern);
        }
        if (req.http.X-Pool) {
          ban("obj.http.X-Pool ~ " + req.http.X-Pool);
        }
        return (synth(200, "Purged"));
    }

    if (req.method != "GET" &&
        req.method != "HEAD" &&
        req.method != "PUT" &&
        req.method != "POST" &&
        req.method != "TRACE" &&
        req.method != "OPTIONS" &&
        req.method != "DELETE") {
          /* Non-RFC2616 or CONNECT which is weird. */
          return (pipe);
    }

    # We only deal with GET and HEAD by default
    if (req.method != "GET" && req.method != "HEAD") {
        return (pass);
    }

    # Bypass shopping cart, checkout and search requests
    if (req.url ~ "/checkout" || req.url ~ "/catalogsearch") {
        return (pass);
    }

    # Bypass health check requests
    if (req.url ~ "/health_check.php") {
        return (pass);
    }

    # Set initial grace period usage status
    set req.http.grace = "none";

    # normalize url in case of leading HTTP scheme and domain
    set req.url = regsub(req.url, "^http[s]?://", "");

    # collect all cookies
    std.collect(req.http.Cookie);

    # Compression filter. See https://www.varnish-cache.org/trac/wiki/FAQ/Compression
    if (req.http.Accept-Encoding) {
        if (req.url ~ "\.(jpg|jpeg|png|gif|gz|tgz|bz2|tbz|mp3|ogg|swf|flv)$") {
            # No point in compressing these
            unset req.http.Accept-Encoding;
        } elsif (req.http.Accept-Encoding ~ "gzip") {
            set req.http.Accept-Encoding = "gzip";
        } elsif (req.http.Accept-Encoding ~ "deflate" && req.http.user-agent !~ "MSIE") {
            set req.http.Accept-Encoding = "deflate";
        } else {
            # unknown algorithm
            unset req.http.Accept-Encoding;
        }
    }

    # Remove all marketing get parameters to minimize the cache objects
    if (req.url ~ "(\?|&)(gclid|cx|ie|cof|siteurl|zanpid|origin|fbclid|mc_[a-z]+|utm_[a-z]+|_bta_[a-z]+)=") {
        set req.url = regsuball(req.url, "(gclid|cx|ie|cof|siteurl|zanpid|origin|fbclid|mc_[a-z]+|utm_[a-z]+|_bta_[a-z]+)=[-_A-z0-9+()%.]+&?", "");
        set req.url = regsub(req.url, "[?|&]+$", "");
    }

    # Static files caching
    if (req.url ~ "^/(pub/)?(media|static)/") {
        # Static files should not be cached by default
        return (pass);

        # But if you use a few locales and don't use CDN you can enable caching static files by commenting previous line (#return (pass);) and uncommenting next 3 lines
        #unset req.http.Https;
        #unset req.http.X-Forwarded-Proto;
        #unset req.http.Cookie;
    }

    return (hash);
}

sub vcl_hash {
    if (req.http.cookie ~ "X-Magento-Vary=") {
        hash_data(regsub(req.http.cookie, "^.*?X-Magento-Vary=([^;]+);*.*$", "\1"));
    }

    # For multi site configurations to not cache each other's content
    if (req.http.host) {
        hash_data(req.http.host);
    } else {
        hash_data(server.ip);
    }

    if (req.url ~ "/graphql") {
        call process_graphql_headers;
    }

    # To make sure http users don't see ssl warning
    if (req.http.X-Forwarded-Proto) {
        hash_data(req.http.X-Forwarded-Proto);
    }

}

sub process_graphql_headers {
    if (req.http.Store) {
        hash_data(req.http.Store);
    }
    if (req.http.Content-Currency) {
        hash_data(req.http.Content-Currency);
    }
}

sub vcl_backend_response {

    set beresp.grace = 3d;

    if (beresp.http.content-type ~ "text") {
        set beresp.do_esi = true;
    }

    if (bereq.url ~ "\.js$" || beresp.http.content-type ~ "text") {
        set beresp.do_gzip = true;
    }

    if (beresp.http.X-Magento-Debug) {
        set beresp.http.X-Magento-Cache-Control = beresp.http.Cache-Control;
    }

    # cache only successfully responses and 404s
    if (beresp.status != 200 && beresp.status != 404) {
        set beresp.ttl = 0s;
        set beresp.uncacheable = true;
        return (deliver);
    } elsif (beresp.http.Cache-Control ~ "private") {
        set beresp.uncacheable = true;
        set beresp.ttl = 86400s;
        return (deliver);
    }

    # validate if we need to cache it and prevent from setting cookie
    if (beresp.ttl > 0s && (bereq.method == "GET" || bereq.method == "HEAD")) {
        unset beresp.http.set-cookie;
    }

   # If page is not cacheable then bypass varnish for 2 minutes as Hit-For-Pass
   if (beresp.ttl <= 0s ||
       beresp.http.Surrogate-control ~ "no-store" ||
       (!beresp.http.Surrogate-Control &&
       beresp.http.Cache-Control ~ "no-cache|no-store") ||
       beresp.http.Vary == "*") {
        # Mark as Hit-For-Pass for the next 2 minutes
        set beresp.ttl = 120s;
        set beresp.uncacheable = true;
    }

    return (deliver);
}

sub vcl_deliver {
    if (resp.http.X-Magento-Debug) {
        if (resp.http.x-varnish ~ " ") {
            set resp.http.X-Magento-Cache-Debug = "HIT";
            set resp.http.Grace = req.http.grace;
        } else {
            set resp.http.X-Magento-Cache-Debug = "MISS";
        }
    } else {
        unset resp.http.Age;
    }

    # Not letting browser to cache non-static files.
    if (resp.http.Cache-Control !~ "private" && req.url !~ "^/(pub/)?(media|static)/") {
        set resp.http.Pragma = "no-cache";
        set resp.http.Expires = "-1";
        set resp.http.Cache-Control = "no-store, no-cache, must-revalidate, max-age=0";
    }

    unset resp.http.X-Magento-Debug;
    unset resp.http.X-Magento-Tags;
    unset resp.http.X-Powered-By;
    unset resp.http.Server;
    unset resp.http.X-Varnish;
    unset resp.http.Via;
    unset resp.http.Link;
}

sub vcl_hit {
    if (obj.ttl >= 0s) {
        # Hit within TTL period
        return (deliver);
    }
    if (std.healthy(req.backend_hint)) {
        if (obj.ttl + 300s > 0s) {
            # Hit after TTL expiration, but within grace period
            set req.http.grace = "normal (healthy server)";
            return (deliver);
        } else {
            # Hit after TTL and grace expiration
            return (miss);
        }
    } else {
        # server is not healthy, retrieve from cache
        set req.http.grace = "unlimited (unhealthy server)";
        return (deliver);
    }
}
```

**Comment by tschirmer** [comment]
That seems right to me. I'll keep looking here. We may have had more than 1 varnish instance running  in the deployment (which would be ideal).

**Comment by martin-helmich** [comment]
Agreed, the VCL file (looking at the generated part) looks alright to me.

I'm wondering if Varnish maybe keeps some internal state of previous backend servers (including healthchecks) used in older versions of the VCL, even if they're not used anymore (actually, `boot` only the initial version of the VCL file that is generated on startup; whenever the backend pod configuration changes during run-time, a new version of the VCL is generated dynamically and loaded).

Can you check how many versions of the VCL are present in your Varnish instance (using `xcl.list`)?

**Comment by tschirmer** [comment]
vcl.list
200
available   cold/cold          0 boot
available   warm/warm          0 k8s-upstreamcfg-1
available   warm/warm          0 k8s-upstreamcfg-2
available   warm/warm          0 k8s-upstreamcfg-3
available   warm/warm          0 k8s-upstreamcfg-4
available   warm/warm          0 k8s-upstreamcfg-5
available   warm/warm          0 k8s-upstreamcfg-6
available   warm/warm          0 k8s-upstreamcfg-7
available   warm/warm          0 k8s-upstreamcfg-8
available   warm/warm          0 k8s-upstreamcfg-9
available   warm/warm          0 k8s-upstreamcfg-10
available   warm/warm          0 k8s-upstreamcfg-11
available   warm/warm          0 k8s-upstreamcfg-12
available   warm/warm          0 k8s-upstreamcfg-13
available   warm/warm          0 k8s-upstreamcfg-14
available   warm/warm          0 k8s-upstreamcfg-15
available   warm/warm          0 k8s-upstreamcfg-16
available   warm/warm          0 k8s-upstreamcfg-17
available   warm/warm          0 k8s-upstreamcfg-18
available   warm/warm          0 k8s-upstreamcfg-19
available   warm/warm          0 k8s-upstreamcfg-20
available   warm/warm          0 k8s-upstreamcfg-21
active      warm/warm         23 k8s-upstreamcfg-22

**Comment by martin-helmich** [comment]
Thanks for the excerpt.

Did some quick reading on this -- apparently, each VCL has a separate set of health checks, and "warm" VCLs keep their health checks active ([docs](https://varnish-cache.org/docs/4.1/whats-new/changes.html#warm-and-cold-vcl-configurations)). There's a run-time parameter called `vcl_cooldown` that specifies after which interval a VCL should automatically transition from "warm" to "cold" -- with a default of 600 seconds ([docs](https://varnish-cache.org/docs/trunk/reference/varnishd.html#vcl-cooldown)).

I could imagine that the VCL state must be set to `auto` for this automatic cooldown to actually happen. I'll look into this some more soon.

**Comment by tschirmer** [comment]
ok awesome, does that need to be set in my VCL or is that something we need to set on startup of the pod?

**Comment by tschirmer** [comment]
It looks like we need to run this:
`vcl.state k8s-upstreamcfg-6 cold`

on the previous config on each change of pods in the deployment.

**Comment by tschirmer** [comment]
Just did that between scale events:

```
 vcl.list
200
available   cold/cold          0 boot
available   warm/warm          0 k8s-upstreamcfg-1
available   warm/warm          0 k8s-upstreamcfg-2
available   warm/warm          0 k8s-upstreamcfg-3
available   warm/warm          0 k8s-upstreamcfg-4
available   warm/warm          0 k8s-upstreamcfg-5
available   warm/warm          0 k8s-upstreamcfg-6
available   warm/warm          0 k8s-upstreamcfg-7
available   warm/warm          0 k8s-upstreamcfg-8
available   warm/warm          0 k8s-upstreamcfg-9
available   warm/warm          0 k8s-upstreamcfg-10
active      warm/warm          0 k8s-upstreamcfg-11

vcl.state k8s-upstreamcfg-10 cold
200

vcl.state k8s-upstreamcfg-9 cold
200

vcl.state k8s-upstreamcfg-8 cold
200

vcl.state k8s-upstreamcfg-7 cold
200

vcl.state k8s-upstreamcfg-6 cold
200

vcl.state k8s-upstreamcfg-5 cold
200

vcl.state k8s-upstreamcfg-4 cold
200

vcl.state k8s-upstreamcfg-3 cold
200

vcl.state k8s-upstreamcfg-2 cold
200

vcl.state k8s-upstreamcfg-1 cold
200

vcl.state vcl.list
200
available   cold/cold          0 boot
available   cold/cold          0 k8s-upstreamcfg-1
available   cold/cold          0 k8s-upstreamcfg-2
available   cold/cold          0 k8s-upstreamcfg-3
available   cold/cold          0 k8s-upstreamcfg-4
available   cold/cold          0 k8s-upstreamcfg-5
available   cold/cold          0 k8s-upstreamcfg-6
available   cold/cold          0 k8s-upstreamcfg-7
available   cold/cold          0 k8s-upstreamcfg-8
available   cold/cold          0 k8s-upstreamcfg-9
available   cold/cold          0 k8s-upstreamcfg-10
active      warm/warm          0 k8s-upstreamcfg-11

```


and it appears to be acting as expected:

```
127.0.0.1 -  02/Mar/2020:05:36:35 +0000 "GET /health_check.php" 200
192.168.217.94:80 192.168.187.124 - - [02/Mar/2020:05:36:35 +0000] "GET /health_check.php HTTP/1.1" 200 500 "-" "-"
127.0.0.1 -  02/Mar/2020:05:36:37 +0000 "GET /health_check.php" 200
192.168.217.94:80 192.168.187.124 - - [02/Mar/2020:05:36:37 +0000] "GET /health_check.php HTTP/1.1" 200 500 "-" "-"
127.0.0.1 -  02/Mar/2020:05:36:40 +0000 "GET /health_check.php" 200
192.168.217.94:80 192.168.187.124 - - [02/Mar/2020:05:36:40 +0000] "GET /health_check.php HTTP/1.1" 200 500 "-" "-"
127.0.0.1 -  02/Mar/2020:05:36:42 +0000 "GET /health_check.php" 200
192.168.217.94:80 192.168.187.124 - - [02/Mar/2020:05:36:42 +0000] "GET /health_check.php HTTP/1.1" 200 500 "-" "-"
127.0.0.1 -  02/Mar/2020:05:36:45 +0000 "GET /health_check.php" 200
192.168.217.94:80 192.168.187.124 - - [02/Mar/2020:05:36:45 +0000] "GET /health_check.php HTTP/1.1" 200 500 "-" "-"
```

**Comment by Hermsi1337** [comment]
Many thanks for your research.  
It looks like `kube-httpcache` must maintain a kind of internal state containing the name of the most recent `vcl` in order to cool it down after loading the new vcl.

**Comment by tschirmer** [comment]
I'm not sure that it even needs to do that. We just need to apply the vcl, and mark it as cold once it's swapped over to the new one after the pod scaling change.

**Comment by martin-helmich** [comment]
The actual Varnish client functionalities are implemented in https://github.com/martin-helmich/go-varnish-client (a side-project of mine). I'll see to it to add a function to change the VCL state that we can then call from `kube-httpcache`.

**Comment by martin-helmich** [comment]
I've hastily hacked together a possible (but completely untested) fix for this in #16. @tschirmer, would you be willing to give the proposed fix a spin to see if it resolves your issue?

**Comment by tschirmer** [comment]
sure, Ill try it oit tomorrow

**Comment by martin-helmich** [comment]
Found an even better fix; the controller explicitly creates new VCL files with state `warm`, which -- in retrospect -- is outright stupid. 🤦‍♂ 

https://github.com/mittwald/kube-httpcache/blob/70b6120475ad80877128905b992d51aa0789b4a5/controller/watch.go#L65-L68

If we use `auto` instead of `warm`, the automatic VCL cooldown should actually work as intended. Updated the fix in #16 accordingly.

**Comment by tschirmer** [comment]
That hasn't worked:

```

vcl.list
200
available   auto/warm          0 boot
available   warm/warm          0 k8s-upstreamcfg-1
active      warm/warm          0 k8s-upstreamcfg-2
```

**Comment by tschirmer** [comment]
^That was on the :latest tag in https://quay.io/repository/spaces/kube-httpcache?tag=latest&tab=tags

Did that include the patch?

**Comment by martin-helmich** [comment]
Oh -- no, `latest` does not include the fix, as it's not merged yet. I've just released a `v0.1.6-alpha2` based directly on #16 tag which should contain the fix.

**Comment by tschirmer** [comment]
no potato,

Just tried that tagged release, and still getting the warm config and the health check saturation.

```
-----------------------------
Varnish Cache CLI 1.0
-----------------------------
Linux,4.14.154-128.181.amzn2.x86_64,x86_64,-junix,-smalloc,-sdefault,-hcritbit
varnish-6.0.1 revision 8d54bec5330c29304979ebf2c425ae14ab80493c

Type 'help' for command list.
Type 'quit' to close CLI session.

vcl.list
200
available   auto/warm          0 boot
available   auto/warm          0 k8s-upstreamcfg-1
active      auto/warm          0 k8s-upstreamcfg-2
```

**Comment by tschirmer** [comment]
OK, more information here:

This is subject to a cooldown period, but each pod added or removed adds extra config; so in a quick-scale event, from 1 pods - 20 pods quickly, the health checks would still quickly overwhelm the servers. We need to manually set them to cold after the new config is activated.

```
vcl.list
200
available   cold/cold          0 boot
available   cold/cold          0 k8s-upstreamcfg-1
available   auto/warm          0 k8s-upstreamcfg-2
available   auto/warm          0 k8s-upstreamcfg-3
available   auto/warm          0 k8s-upstreamcfg-4
active      auto/warm          0 k8s-upstreamcfg-5

vcl.list
200
available   cold/cold          0 boot
available   cold/cold          0 k8s-upstreamcfg-1
available   auto/warm          0 k8s-upstreamcfg-2
available   auto/warm          0 k8s-upstreamcfg-3
available   auto/warm          0 k8s-upstreamcfg-4
active      auto/warm          0 k8s-upstreamcfg-5
```

**Comment by Hermsi1337** [comment]
@martin-helmich maybe we should then move back to your first, "silly", fix? ^^

**Comment by tschirmer** [comment]
@Hermsi1337 no way, this is much better than nothing. The ideal way to do this would be to warm the config, switch is over, then mark the old config as cool.

Right now, it's set to auto, which allows for a cool-down period automatically, but that still causes problems when we scale very quickly (e.g. server 1, then server 2, then server 3 would result in 3x the health checks hitting server1 and overwhelming it).

I've been running the alpha on our stack and we're getting much better performance out of our backend servers while keeping the health checks enabled.

**Comment by Hermsi1337** [comment]
@tschirmer this is actually what the first fix of @martin-helmich does, isn't it ?

https://github.com/mittwald/kube-httpcache/blob/fb33c177ac0405d9af9bbc105ff9cce20ab65533/controller/watch.go#L79

**Comment by tschirmer** [comment]
@Hermsi1337 I hadn't looked at it in the code just yet, I've been tied up with other projects, but that looks like what's happening from me quickly glancing at it. 

If that's packaged into an alpha3, I can deploy and test it, but I'm not sure what's been packaged in the alpha2.

**Comment by martin-helmich** [comment]
`alpha2` was the version with automatic cooldown (`alpha1` was an image that was built incorrectly).

@tschirmer Maybe it would already help to set `vcl_cooldown` to a (much) lower value? The default is 600 seconds, I think. If set to 60 secs (minimum granularity would be 30 secs, according to docs), old VCLs should cool down considerably faster.
 
Alternatively, I'll see if I can reactivate the original bugfix that explicitly cools down old VCLs.

**Comment by tschirmer** [comment]
@martin-helmich I can set the cooldown, but on mass scale events in kubernetes, it will result badly unless that cooldown is very low. I like the idea of explicitly cooling it once the new config is applied.

Let's try that old bugfix and see if we can get it building correctly.

**Comment by martin-helmich** [comment]
Sorry for the delay -- I've reactivated the previous solution from #16 and tagged the `v0.1.6-alpha3` image which should be available shortly, if you want to give it a spin.

**Comment by dealancer** [comment]
@martin-helmich I could run some tests, could you please reassemble this alpa release with the most recent code from master?

**Comment by martin-helmich** [comment]
@dealancer [here](https://github.com/mittwald/kube-httpcache/releases/tag/v0.2.1-alpha.2) you go. 😉

**Comment by dealancer** [comment]
@martin-helmich 

So I did a couple of stress tests with autoscaling of pods, and Varnish works as expected. I was able to see new configs warming up and old configs cooling down. I did not do test for probes as I do not have probes configured in my VCL.

Probably @tschirmer can test for probes issue he had.

**Comment by tschirmer** [comment]
Can confirm this is working as expected in alpha3

**Comment by tschirmer** [comment]
Thought this was finished, but I just had a quick look and I'm still getting multiple checks:
```
10.0.3.93:80 10.0.3.244 - - [23/Apr/2020:06:10:06 +0000] "GET /health_check.php HTTP/1.1" 200 464 "-" "-"
127.0.0.1 -  23/Apr/2020:06:10:06 +0000 "GET /health_check.php" 200
10.0.3.93:80 10.0.3.244 - - [23/Apr/2020:06:10:06 +0000] "GET /health_check.php HTTP/1.1" 200 464 "-" "-"
127.0.0.1 -  23/Apr/2020:06:10:11 +0000 "GET /health_check.php" 200
10.0.3.93:80 10.0.3.244 - - [23/Apr/2020:06:10:11 +0000] "GET /health_check.php HTTP/1.1" 200 464 "-" "-"
127.0.0.1 -  23/Apr/2020:06:10:11 +0000 "GET /health_check.php" 200
10.0.3.93:80 10.0.3.244 - - [23/Apr/2020:06:10:11 +0000] "GET /health_check.php HTTP/1.1" 200 464 "-" "-"
127.0.0.1 -  23/Apr/2020:06:10:16 +0000 "GET /health_check.php" 200
10.0.3.93:80 10.0.3.244 - - [23/Apr/2020:06:10:16 +0000] "GET /health_check.php HTTP/1.1" 200 464 "-" "-"
127.0.0.1 -  23/Apr/2020:06:10:16 +0000 "GET /health_check.php" 200
10.0.3.93:80 10.0.3.244 - - [23/Apr/2020:06:10:16 +0000] "GET /health_check.php HTTP/1.1" 200 464 "-" "-"
```

**Comment by tschirmer** [comment]
Is significantly better than it was originally though:

```
10.0.3.93:80 10.0.3.244 - - [23/Apr/2020:06:11:59 +0000] "GET /health_check.php HTTP/1.1" 200 464 "-" "-"
127.0.0.1 -  23/Apr/2020:06:12:03 +0000 "GET /health_check.php" 200
10.0.3.93:80 10.0.3.244 - - [23/Apr/2020:06:12:03 +0000] "GET /health_check.php HTTP/1.1" 200 464 "-" "-"
127.0.0.1 -  23/Apr/2020:06:12:04 +0000 "GET /health_check.php" 200
10.0.3.93:80 10.0.3.244 - - [23/Apr/2020:06:12:04 +0000] "GET /health_check.php HTTP/1.1" 200 464 "-" "-"
127.0.0.1 -  23/Apr/2020:06:12:08 +0000 "GET /healthz" 200
10.0.3.93:82 10.0.3.162 - - [23/Apr/2020:06:12:08 +0000] "GET /healthz HTTP/1.1" 200 317 "-" "kube-probe/1.15+"
127.0.0.1 -  23/Apr/2020:06:12:09 +0000 "GET /health_check.php" 200
10.0.3.93:80 10.0.3.244 - - [23/Apr/2020:06:12:09 +0000] "GET /health_check.php HTTP/1.1" 200 464 "-" "-"
127.0.0.1 -  23/Apr/2020:06:12:09 +0000 "GET /health_check.php" 200
10.0.3.93:80 10.0.3.244 - - [23/Apr/2020:06:12:09 +0000] "GET /health_check.php HTTP/1.1" 200 464 "-" "-"
127.0.0.1 -  23/Apr/2020:06:12:14 +0000 "GET /health_check.php" 200
```

**Comment by martin-helmich** [comment]
@tschirmer Thanks for checking again. From looking at the logs, it seems that Varnish now (at least roughly) seems to stick to the originally configured 5-second interval (assuming you're still using the configuration from your initial report). However, some of these probes still are run twice (for example, two at 06:12:09) -- I'm not really sure why this is still happening; I could only imagine that Varnish doesn't shut down the probes immediately when switching a VCL file to "cold" state.

I'll see to it that we merge #16 for the time being, since it at least seems to improve things significantly.
